services:
  app:
    build: .
    ports:
      - "5002:5002"
    environment:
      - NODE_ENV=development
      - DB_HOST=database
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - HASH_KEY=${HASH_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - API_KEY=${API_KEY}
      - PORT=${PORT}
    volumes:
      - /home/ronyzs/api/my-express-mysql:/usr/src/app/api
    depends_on:
      - database

  database:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1q2w3e4r
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: